### ISSUE TITLE
Lists can't be nested more than once

### ISSUE THREAD

**Issue by jsunsawyer** [selvinortiz/craft-plugin-doxter#36] opened 2020-02-07 19:14 UTC
I assume that this should be supported if we're trying to match github flavored markdown.

See: https://github.github.com/gfm/#example-287

Craft: 3.4.4.1
Doxter: 3.4.9

**Comment by selvinortiz** [comment] 2020-02-13 05:35
@jsunsawyer Doxter supports lists nested several levels deep.

Given the following ordered and unordered lists:

```
1. Top Level Item
2. Top Level Item 2
  1. Second Level Item
  2. Second Level Item 2
    1. Third Level Item
    2. Third Level Item 2
```

```
- Top Level Item
- Top Level Item 2
  - Second Level Item
  - Second Level Item 2
    - Third Level Item
    - Third Level Item 2
```

Doxter will render the correct multi-level list.

Can you share the bit of markdown that isn't rendering for you so that I can reproduce it?

**Comment by jsunsawyer** [comment] 2020-02-13 17:19
```
1. Top Level Item
2. Top Level Item 2
  1. Second Level Item
  2. Second Level Item 2
    1. Third Level Item
    2. Third Level Item 2
```

Your example renders like the following with just the `|doxter` filter added.

```
<ol>
<li>Top Level Item</li>
<li>Top Level Item 2
<ol>
<li>Second Level Item</li>
<li>Second Level Item 2</li>
<li>Third Level Item</li>
<li>Third Level Item 2</li>
</ol></li>
</ol>
```

Also noticed another issue.

When adding after another list, with multiple returns between, the list continues to chain off the immediate list before it. See screenshots.

**CP view**
![Screen Shot 2020-02-13 at 9 15 37 AM](https://user-images.githubusercontent.com/1007191/74460359-9fdb1f80-4e41-11ea-8b8d-5ca165e4875f.png)

**Front-end view**
![Screen Shot 2020-02-13 at 9 15 52 AM](https://user-images.githubusercontent.com/1007191/74460370-a4073d00-4e41-11ea-8c83-39c8602dc285.png)

Adding an element like `---` between lists renders the lists separately, but nesting is still incorrect for 3rd level lists. Multiple separated lists should be able to render correctly after each other, right?

**Comment by selvinortiz** [comment] 2020-02-28 15:20
@jsunsawyer I've done further testing on this and while I'm not satisfied by how the Markdown parsers handles lists, it seems to be an issue that parsers have not yet entirely solved.

In the example you linked at the beginning of this thread, they recommend using an empty html comment to separate lists.

```
1. List item one
1. List item two
1. List item three
    1. List item one in list two
    1. List item two in list two

<!-- -->

1. List item one
1. List item two
1. List item three
    1. List item one in list two
    1. List item two in list two
```

Another thing is that multilevel nesting is supported by adjusting the spacing and unfortunately, it requires some trial and error, as described in the GFM spec for lists https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#nested-lists

**Comment by selvinortiz** [comment] 2020-02-28 15:20
I'm going to close this issue and add a todo for myself to update the docs with caveats you've found in your testing.

**Closed as completed by selvinortiz** 2020-02-28 15:20 UTC
Labels: enhancement
